version: '3.8'
services:
  web:
    image: node:18.16.0
    user: '${UID}:${GID}'
    working_dir: /app
    env_file: .env
    command: yarn dev --host=0.0.0.0 --port=3000
    volumes:
      - ./web:/app
    ports:
      - 3000:3000
  nginx:
    image: nginx
    ports:
      - 8080:80
